const EVENT_TYPES = {
  VIDEO_UPLOADED: "VIDEO_UPLOADED",
  AI_PLAN_CREATED: "AI_PLAN_CREATED",
  HLS_GENERATED: "HLS_GENERATED",
  SUBTITLE_READY: "SUBTITLE_READY",
  MODERATION_COMPLETE: "MODERATION_COMPLETE",
  THUMBNAIL_READY: "THUMBNAIL_READY",
  VIDEO_READY: "VIDEO_READY",
  VIDEO_FAILED: "VIDEO_FAILED"
};

const VIDEO_STATUS = {
  UPLOADING: "UPLOADING",
  ANALYZING: "ANALYZING",
  PROCESSING: "PROCESSING",
  TRANSCODING: "TRANSCODING",
  READY: "READY",
  FAILED: "FAILED",
  BLOCKED: "BLOCKED",
  REVIEW_REQUIRED: "REVIEW_REQUIRED"
};

const DEFAULT_RESOLUTIONS = ["720p", "480p", "360p"];

module.exports = {
  EVENT_SOURCE: "video-platform",
  EVENT_BUS_NAME: process.env.EVENT_BUS_NAME || "video-platform-events",
  EVENT_TYPES,
  VIDEO_STATUS,
  DEFAULT_RESOLUTIONS
};

